const express = require('express');
const router = express.Router();
const trainerController = require('../controllers/TrainerController');
const verifyToken = require('../middlewares/verifyToken');
const checkRole = require('../middlewares/checkRole');

router.get(
  '/createCourse',
  verifyToken,
  checkRole.trainer,
  trainerController.getCreateCourseView,
);
router.get(
  '/getCourseDetail/:id',
  verifyToken,
  checkRole.trainer,
  trainerController.getCourseDetail,
);
router.get(
  '/createCourseDetail/:id',
  verifyToken,
  checkRole.trainer,
  trainerController.getCreateDetail,
);
router.post(
  '/createCourseChapter/:id',
  verifyToken,
  checkRole.trainer,
  trainerController.postCreateChapter,
);
router.post(
  '/createQuestion/:id',
  verifyToken,
  checkRole.trainer,
  trainerController.postCreateQuestion,
);
router.post(
  '/createquiz/:id',
  verifyToken,
  checkRole.trainer,
  trainerController.postCreateQuiz,
);
router.post(
  '/createVideo/:id',
  verifyToken,
  checkRole.trainer,
  trainerController.postCreateVideo,
);
router.post(
  '/createCourse',
  verifyToken,
  checkRole.trainer,
  trainerController.postCreateCourse,
);
router.get(
  '/:id/updateCourse',
  verifyToken,
  checkRole.trainer,
  trainerController.getUpdateCourseView,
);
router.get(
  '/:id/listTrainee',
  verifyToken,
  checkRole.trainer,
  trainerController.getListTraineeView,
);
router.patch(
  '/:id/updateCourse',
  verifyToken,
  checkRole.trainer,
  trainerController.updateCourse,
);
router.delete(
  '/:id/deleteCourse',
  verifyToken,
  checkRole.trainer,
  trainerController.deleteCourse,
);
router.get(
  '/',
  verifyToken,
  checkRole.trainer,
  trainerController.listTrainerCourse,
);
module.exports = router;
